"""Initial migration.

Revision ID: 3ff8b9f1984f
Revises: 
Create Date: 2023-03-30 17:21:10.944200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff8b9f1984f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mindfultext',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('AFFIRMATION', 'ADVICE', 'REFLECTION', 'MANTRA', name='mindfultexttype'), nullable=False),
    sa.Column('is_quote', sa.Boolean(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('MEDITATION', 'YOGA' 'AMBIANCE', name='videotype'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('mindfultext')
    # ### end Alembic commands ###
